### ISSUE TITLE
[Workflow] Automatically run `black`, `flake8`, `isort` via Github Action

### ISSUE THREAD

**Issue by benjaminye** [georgian-io/LLM-Finetuning-Hub#103]
**Is your feature request related to a problem? Please describe.**
- Automatic formatting and linting to improve code consistency

**Describe the solution you'd like**
- Have pre-commit hooks that run before commits 
- [Example](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)

**Describe alternatives you've considered**
- I've been manually running `black` from time to time on the whole repo, but not the best solution for collaboration

**Comment by benjaminye** [comment]
- Found an all-in-one solution that's faster: https://github.com/astral-sh/ruff

**Comment by truskovskiyk** [comment]
@benjaminye, It might not be pre-commit hooks, but just CI check that we pass the style. Not bug fun of pre-commit hooks to be honest

**Comment by benjaminye** [comment]
Closed as implemented by https://github.com/georgian-io/LLM-Finetuning-Hub/pull/116
