### ISSUE TITLE
[Feature Request]: Official Dockerfile / Docker-Compose

### ISSUE THREAD

**Issue by sammcj** [georgian-io/LLM-Finetuning-Hub#34]
It would be nice if this project had an official Docker image and a docker-compose example - that would make trying it out easier for a lot of folks 😄

**Comment by anthonyprinaldi** [comment]
@sammcj there are a few different tasks for the project (i.e., fine-tuning, evaluation, and inference). Which of these are of interest to you?

**Comment by RohitSaha** [comment]
@anthonyprinaldi It'd be great if we can start with the fine-tuning piece. The current requirements.txt file contains all the packages one needs to finetune the models so would be nice if we can dockerize that bit first.

**Comment by sammcj** [comment]
@anthonyprinaldi personally I agree with Rohit, fine-tuning is something that currently isn't as easy for most folks to get into where as there's a lot of front ends for inference.

**Comment by mariia-georgian** [comment]
@anthonyprinaldi thanks a lot for the contribution! However i am now trying to run the .sh script from the PR  `./finetune.sh \
		flan-t5 \
		classification \
		--peft_method prefix --prefix_tokens 20 --epochs 5 ` 
and get the output "Task classification does not exist." I echoed `"./$MODEL/${NAME_MAPPER[$MODEL]}_${TASK}.py"` and it looked like "./flan-t5/redpajama_classification.py" which doesn't make sense, cause the code seems right

**Comment by mariia-georgian** [comment]
@anthonyprinaldi thanks for the contribution! I tried to run docker-compose and it got stuck on training, I don't see the progress going 
<img width="922" alt="Screenshot 2023-10-25 at 3 30 54 PM" src="https://github.com/georgian-io/LLM-Finetuning-Hub/assets/138687793/f4408075-8215-4362-8b3e-7a56cc3d5cb5">

**Comment by RohitSaha** [comment]
@sammcj We finally have a dockerfile added to the repository. 

@benjaminye can help answer any questions you may have.

Please let us know if you have more feedback to give. And we are always looking for external collaborators :)
