### ISSUE TITLE
Latency and Throughput Calculation

### ISSUE THREAD

**Issue by jerin-scalers-ai** [georgian-io/LLM-Finetuning-Hub#58]
How is latency and throughput is being measured for Llama 2 7B model inference benchmarking using TGI. [Reference](https://github.com/georgian-io/LLM-Finetuning-Hub#benchmarks)

**Comment by mariia-georgian** [comment]
@jerin-scalers-ai we used [vegeta](https://github.com/tsenart/vegeta) for sending requests and it was automatically calculating latency and throughput based on performance.

**Comment by jerin-scalers-ai** [comment]
@mariia-georgian Thanks for letting me know.
