### ISSUE TITLE
Inferencing script not executable due to package dependency errors 

### ISSUE THREAD

**Issue by viveksingh-ctrl** [georgian-io/LLM-Finetuning-Hub#68]
I tried to go through the [README](https://github.com/georgian-io/LLM-Finetuning-Hub/blob/main/requirements.txt) file as mentioned, and once i execute `llama2_baseline_inference.py` I am thrown with the error 

```ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` ``` 

even though the packages are installed in my environment. I was able to circumvent this problem by upgrading my `datasets` library using `pip install -U datasets` and now I received one other error as given below in this [link](https://stackoverflow.com/questions/77671277/valueerror-invalid-pattern-can-only-be-an-entire-path-component)

To avoid this issue, I downgraded my `transformers` library to 4.3 and currently, I am unable to download some of the checkpoints. I feel the packages need to be revamped with the latest versions

**Comment by viveksingh-ctrl** [comment]
<img width="993" alt="Screenshot 2024-02-05 at 8 12 23 PM" src="https://github.com/georgian-io/LLM-Finetuning-Hub/assets/87975235/865e99f8-1428-4869-8437-02166eed10d4">

current issue is this one now

**Comment by benjaminye** [comment]
Hi Vivek, if you're using a conda environment, can you send the output of:
```shell
conda list -e
```
or if not using conda,
```shell
pip3 freeze
```

Thanks!
